[project]
name = "Flyan"
version = "0.1.0"
description = "Open source unofficial API wrappper to get flight data from RyanAir."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "httpx>=0.27.2",
    "pydantic>=2.9.2",
    "tenacity>=9.0.0",
]
